serverFiles:
  prometheus.yml:
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: "fin-control-cluster"
        static_configs:
          - targets: ["52.188.26.21:8080"]

server:
  service:
    type: NodePort
    nodePort: 30900
